---

- name: include os-specific installation
  include: "setup-{{ elasticsearch_os_family }}.yml"

- name: set limits for elasticsearch
  template: >
    src=limits.conf.j2
    dest=/etc/security/limits.d/elasticsearch.conf
    owner=root
    group=root
    mode=0644

- name: template elasticsearch defaults
  template: >-
    src=elasticsearch.j2
    dest={{ elasticsearch_defaults_path }}
    owner=root
    group=root
    mode=0644
  notify: restart elasticsearch

- name: template elasticsearch.yml
  template: >-
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root
    group={{ _es_combined.group }}
    mode=0750
  notify: restart elasticsearch

- name: install plugins
  command: >
    {{ _es_combined.path_home }}/bin/plugin install {{ item.path }}
    creates={{ _es_combined.path_plugins }}/{{ item.name }}
  with_items: "{{ _es_combined.plugins }}"

- name: enable and start elasticsearch
  service: name=elasticsearch enabled=yes state=started
