# wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
#$ echo "deb https://packages.elastic.co/kibana/4.1/debian stable main" | sudo tee -a /etc/apt/sources.list
#$ sudo apt-get update
#$ sudo apt-get install kibana
- name: Enable kibana Repository
  apt_repository: repo="{{ _kibana_combined.apt_repo }}"
                  state=present
  tags: kibana_repo

- name: Add kibana Repo Key
  apt_key: url="{{ _kibana_combined.repo_key }}"
           state=present
  tags: kibana_repo

- name: Install kibana
  apt: pkg=kibana
       update_cache=yes
       state=latest
  tags: kibana_install
