---
- name: Enable Logstash Repository
  apt_repository: >
    repo="{{ _logstash_combined.apt_repo }}"
    state=present
  tags: logstash_repo

- name: Add Logstash Repo Key
  apt_key: >
    url="{{ _logstash_combined.repo_key }}"
    state=present
  tags: logstash_repo

- name: Install Logstash
  apt: >
    pkg=logstash
    update_cache=yes
    state=latest
  tags: logstash_install

- debug: var=logstash_defaults

- name: Configure default settings for Logstash (Debian only. Upstart on Ubuntu won't be touched)
  template: >-
    src=defaults.conf.j2
    dest={{ _logstash_debian_default }}
    owner=root
    group=root
    mode=0644
  notify:
   - restart logstash
  tags:
   - logstash_defaults
