# Loop though logstash_plugins and install them
- name: Removing Plugins if they exist
  action: >
    shell bin/plugin uninstall "{{ item.name }}"
    chdir="{{ _logstash_combined.home_dir }}"
  with_items: "{{ logstash_plugins }}"
  ignore_errors: yes
- name: Installing Plugins by Name
  action: >
    shell bin/plugin install "{{ item.name }}"
    chdir="{{ _logstash_combined.home_dir }}"
  with_items: "{{ logstash_plugins }}"
  ignore_errors: no
